# Generated by Django 2.2.5 on 2021-05-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='room',
            name='house_rules',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
